//! Battery product group plugin — EU Battery Regulation 2023/1542.
//!
//! Reference implementation of the [`DppProductGroupPlugin`] contract on top of
//! `dpp-plugin-sdk`. The crate contains only the plugin's domain logic — the
//! Wasm ABI (`alloc`/`dealloc`/`describe`/`validate`/`calculate_metrics`/
//! `generate_passport`) is generated by [`export_plugin!`].
//!
//! ## ProductGroup vs. product category
//!
//! "battery" is a **product group** — the EU delegated-act bucket the host dispatches
//! on. It is distinct from a *product category* (e.g. `"portable"`,
//! `"industrial"`, `"ev"`), which the Battery Regulation carries as the
//! `batteryType` data field. The product group selects this plugin; the product
//! category is an attribute this plugin may branch on internally. The two are
//! never interchangeable as dispatch keys.

use dpp_plugin_sdk::export_plugin;
use dpp_plugin_sdk::rules::batteries::degradation::{
    Annex7ParameterSet, annex_vii_parameter_set_for,
};
use dpp_plugin_sdk::rules::batteries::passport_content::{fields_not_applicable, mandatory_fields};
use dpp_plugin_sdk::rules::batteries::recycled_content::{
    Art8Category, Art8Phase, Art8SecondLife, RecycledContentInput, art8_category_for,
    art8_phase_for, art8_shortfalls_2031, art8_shortfalls_2036, chemistry_regulated_metals,
    recycled_content_chemistry_conflicts,
};
use dpp_plugin_sdk::rules::common::date::CalendarDate;
use dpp_plugin_sdk::traits::{
    DppProductGroupPlugin, METRIC_CO2E_SCORE, PluginComplianceStatus, PluginError, PluginFinding,
    PluginIdentity, PluginInput, PluginResult, SchemaVersionRange,
};
use dpp_plugin_sdk::validate::{Validator, num};
use serde_json::{Value, json};

#[derive(Default)]
struct BatteryPlugin;

impl DppProductGroupPlugin for BatteryPlugin {
    fn plugin_identity(&self) -> PluginIdentity {
        PluginIdentity {
            product_group: "battery",
            name: "Odal Node Battery Plugin",
            version: env!("CARGO_PKG_VERSION"),
            description: "EU Battery Regulation 2023/1542 structural validation and metrics",
        }
    }

    // Battery schema ships as v1.0.0 through v2.5.0 (Annex XIII + Annex VII).
    fn schema_version_range(&self) -> SchemaVersionRange {
        SchemaVersionRange {
            min_version: "1.0.0".into(),
            max_version: "2.6.0".into(),
        }
    }

    fn validate_input(&self, input: &PluginInput) -> Result<(), PluginError> {
        Validator::new(input)
            .require_gtin("gtin")
            .require_str("batteryChemistry")
            .require_positive("nominalVoltageV")
            .require_positive("nominalCapacityAh")
            .require_non_negative("co2ePerUnitKg")
            .optional_positive_int("expectedLifetimeCycles")
            .optional_pct("recycledContentCobaltPct")
            .optional_pct("recycledContentLithiumPct")
            .optional_pct("recycledContentNickelPct")
            .optional_pct("recycledContentLeadPct")
            .optional_pct("stateOfHealthPct")
            .optional_pct("initialRoundTripEfficiencyPct")
            .optional_pct("roundTripEfficiencyAtHalfCycleLifePct")
            .optional_pct("renewableContentPct")
            .optional_pct("capacityThresholdForExhaustionPct")
            .finish()
    }

    fn calculate_metrics(&self, input: &PluginInput) -> Result<PluginResult, PluginError> {
        // Metrics are only meaningful for structurally valid input.
        self.validate_input(input)?;

        let co2e = num(input, "co2ePerUnitKg");

        // The Battery Regulation tracks recycled content *per metal* (cobalt,
        // lithium, nickel, lead), so the flat `recycled_content_pct` metric is
        // left unset and the full per-metal breakdown travels under `extra`.
        //
        // This used to report the mean of the declared metals there. Art. 8(2)
        // and 8(3) set a separate minimum per metal, over two different
        // measurement bases — for cobalt, lithium and nickel the share is
        // measured in *active materials*, for lead it is the share *present in
        // the battery*. A mean conflates four thresholds and two denominators
        // into one figure the regulation never asks for, and a reader takes it
        // for a compliance number. Nothing downstream can undo that, because by
        // then the four inputs are gone.
        let cobalt = num(input, "recycledContentCobaltPct");
        let lithium = num(input, "recycledContentLithiumPct");
        let nickel = num(input, "recycledContentNickelPct");
        let lead = num(input, "recycledContentLeadPct");

        let chemistry = input
            .get("batteryChemistry")
            .and_then(Value::as_str)
            .unwrap_or("");
        let battery_type = input
            .get("batteryType")
            .and_then(Value::as_str)
            .unwrap_or("");
        let regulated = chemistry_regulated_metals(chemistry);
        // Energy capacity for the Phase-1 ">2 kWh" scoping threshold: the rated
        // value if given, else nominal V × Ah (both required, so always known).
        let capacity_kwh = num(input, "ratedCapacityKwh").or_else(|| {
            match (
                num(input, "nominalVoltageV"),
                num(input, "nominalCapacityAh"),
            ) {
                (Some(v), Some(ah)) => Some(v * ah / 1000.0),
                _ => None,
            }
        });

        let mut warnings: Vec<PluginFinding> = Vec::new();

        warnings.extend(annex_xiii_content_findings(input, battery_type));
        warnings.extend(annex_vii_state_of_health_finding(input, battery_type));

        // Data integrity: recycled content declared for a metal the chemistry
        // does not contain (e.g. cobalt on an LFP cell) is a contradiction —
        // surface it as an advisory rather than folding it into the mean silently.
        for metal in recycled_content_chemistry_conflicts(chemistry, cobalt, lithium, nickel, lead)
        {
            let field = match metal {
                "cobalt" => "/recycledContentCobaltPct",
                "lithium" => "/recycledContentLithiumPct",
                "nickel" => "/recycledContentNickelPct",
                "lead" => "/recycledContentLeadPct",
                _ => "",
            };
            warnings.push(PluginFinding::new(
                format!("battery.recycled_content.{metal}_not_in_chemistry"),
                field,
                format!(
                    "Declared {metal} recycled content, but a {chemistry} battery contains \
                     no {metal} — check the declaration."
                ),
            ));
        }

        // Recycled-content targets (EU 2023/1542 Art. 8(2)/(3)). Which phase
        // binds is decided by the date the battery was placed on the EU market,
        // never by today's date: Art. 8 attaches its duties at placing on the
        // market, so a battery lawfully placed in 2030 never acquires the 2031
        // minima. Shortfalls are scoped to the metals the declared chemistry
        // actually contains (an LFP cell has no cobalt or nickel), and are always
        // advisory — the overall status is NotAssessed.
        let art8_category = art8_category_for(battery_type, capacity_kwh);

        // Art. 8(1) requires the shares "for each battery model per year and per
        // manufacturing plant". A percentage without both anchors is not that
        // declaration — it is an unattributed number, and no reader can tell
        // which production run it describes.
        let declared_any_share = [cobalt, lithium, nickel, lead].iter().any(Option::is_some);
        if declared_any_share
            && art8_category != Art8Category::NotCovered
            && input.get("recycledContentReportingYear").is_none()
        {
            warnings.push(PluginFinding::new(
                "battery.recycled_content.reporting_year_missing",
                "/recycledContentReportingYear",
                "Recycled-content shares are declared without a reporting year.                  EU 2023/1542 Art. 8(1) requires them per battery model, per year                  and per manufacturing plant, so a share without its year is not                  the Art. 8(1) declaration.",
            ));
        }

        if art8_category != Art8Category::NotCovered {
            let scoped = RecycledContentInput {
                cobalt_pct: if regulated.cobalt { cobalt } else { None },
                lithium_pct: if regulated.lithium { lithium } else { None },
                nickel_pct: if regulated.nickel { nickel } else { None },
                lead_pct: if regulated.lead { lead } else { None },
            };
            let placed_on_market = input
                .get("placedOnMarketDate")
                .and_then(Value::as_str)
                .and_then(CalendarDate::parse_iso);

            match placed_on_market {
                // Declining to guess is the whole point. Defaulting to "today"
                // is what produces retroactively wrong findings once a phase
                // begins, so say what is missing instead.
                None => warnings.push(PluginFinding::new(
                    "battery.recycled_content.market_date_missing",
                    "/placedOnMarketDate",
                    "Cannot determine which EU 2023/1542 Art. 8 recycled-content phase \
                     applies without a valid placedOnMarketDate (YYYY-MM-DD). The minimum \
                     shares attach by the date the battery was placed on the EU market.",
                )),
                Some(date) => {
                    let (shortfalls, year, standing) =
                        match art8_phase_for(art8_category, date, art8_second_life(input)) {
                        Art8Phase::Phase1 => (
                            art8_shortfalls_2031(&scoped),
                            "2031",
                            "binding for this battery",
                        ),
                        Art8Phase::Phase2 => (
                            art8_shortfalls_2036(&scoped),
                            "2036",
                            "binding for this battery",
                        ),
                        // In scope, but placed on the market before the phase
                        // began. Reported as forward-looking guidance rather
                        // than dropped: useful to know, but not a duty this
                        // battery carries.
                        Art8Phase::NotYetBinding => match art8_category {
                            Art8Category::Lmt => (
                                art8_shortfalls_2036(&scoped),
                                "2036",
                                "not binding for this battery — Art. 8(3) applies to LMT \
                                 batteries placed on the market from 18 Aug 2036",
                            ),
                            _ => (
                                art8_shortfalls_2031(&scoped),
                                "2031",
                                "not binding for this battery — Art. 8(2) applies to \
                                 batteries placed on the market from 18 Aug 2031",
                            ),
                        },
                        // Art. 8(4): the paragraphs do not apply at all. No
                        // shortfall is reportable, and reporting one would
                        // assert a duty the Regulation removed.
                        Art8Phase::ExemptSecondLife | Art8Phase::NotCovered => {
                            (Vec::new(), "", "")
                        }
                    };
                    for sf in shortfalls {
                        let field = match sf.material {
                            "cobalt" => "/recycledContentCobaltPct",
                            "lithium" => "/recycledContentLithiumPct",
                            "nickel" => "/recycledContentNickelPct",
                            "lead" => "/recycledContentLeadPct",
                            _ => "",
                        };
                        warnings.push(PluginFinding::new(
                            format!(
                                "battery.recycled_content.{}_below_{year}_target",
                                sf.material
                            ),
                            field,
                            format!(
                                "Declared {} recycled content {:.1}% is below the EU 2023/1542 \
                                 Art. 8 minimum of {:.0}% ({standing}).",
                                sf.material, sf.declared_pct, sf.required_pct
                            ),
                        ));
                    }
                }
            }
        }

        // Plausibility: rated energy (kWh) vs nominal V×Ah. A gross mismatch
        // (outside [0.5×, 2×]) is almost always a unit-entry error (e.g. Wh
        // typed as kWh). Advisory only — never blocks.
        if let (Some(v), Some(ah), Some(kwh)) = (
            num(input, "nominalVoltageV"),
            num(input, "nominalCapacityAh"),
            num(input, "ratedCapacityKwh"),
        ) {
            let nominal_kwh = v * ah / 1000.0;
            if kwh > 0.0 && nominal_kwh > 0.0 {
                let ratio = kwh / nominal_kwh;
                if !(0.5..=2.0).contains(&ratio) {
                    warnings.push(PluginFinding::new(
                        "battery.rated_capacity.inconsistent_with_nominal",
                        "/ratedCapacityKwh",
                        format!(
                            "Rated capacity {kwh:.2} kWh is inconsistent with nominal \
                             {v}V × {ah}Ah = {nominal_kwh:.2} kWh — check units.",
                        ),
                    ));
                }
            }
        }

        // CO2e compliance thresholds are set by pending delegated acts under
        // Art. 7(2); a binding pass/fail determination is not yet possible, so
        // the status stays NotAssessed and co2e is passed through as a metric.
        let result = PluginResult::new(PluginComplianceStatus::NotAssessed)
            .maybe_metric(METRIC_CO2E_SCORE, co2e)
            .with_extra(json!({
                "recycledContentByMetal": {
                    "cobaltPct": cobalt,
                    "lithiumPct": lithium,
                    "nickelPct": nickel,
                    "leadPct": lead,
                },
                "carbonFootprintClass": input.get("carbonFootprintClass"),
                "batteryType": input.get("batteryType"),
            }));
        Ok(warnings
            .into_iter()
            .fold(result, PluginResult::with_warning))
    }

    fn generate_passport(&self, input: PluginInput) -> Result<Value, PluginError> {
        // Battery data is stored verbatim once structurally valid; no
        // normalisation is required by the schema today.
        self.validate_input(&input)?;
        Ok(input)
    }
}

/// Annex XIII content the battery's category owes, and content it must not
/// carry — the Commission's per-category data-point table, read at create time.
///
/// The binding check is the host's, at first publish. Repeating it here is not
/// duplication of the *rule* — the table has one home in `dpp-rules` and both
/// callers read it — but of the *moment*: a passport that will be refused at
/// publish should not have to reach publish to discover why, and a field the
/// guidance says must not be filled is never mentioned there at all.
///
/// Missing content is reported as **one** finding rather than one per field.
/// Read Art. 8(4)'s second-life test off the payload's `batteryStatus`.
///
/// `batteryStatus` is Annex XIII point 4(c), whose closed set is
/// `original | repurposed | re-used | remanufactured | waste`. Three of those
/// name an Art. 8(4) operation. `waste` does not: end-of-life is not preparation
/// for re-use, and a waste battery is not being placed on the market.
///
/// A battery reaching one of those three states was necessarily on the market
/// before it — you cannot repurpose what was never placed — so the article's
/// second condition is satisfied by the status itself. That inference is the
/// operator's to stand behind; the field is theirs to declare.
///
/// **Absent or unrecognised reads as `None`.** Art. 8(4) is an exemption, and an
/// undeclared status is not evidence of one. Excusing a duty on a missing field
/// is the error an authority finds later; asserting one we should not is the
/// error the operator can see and correct now.
fn art8_second_life(input: &PluginInput) -> Art8SecondLife {
    match input.get("batteryStatus").and_then(Value::as_str) {
        Some("repurposed" | "re-used" | "remanufactured") => {
            Art8SecondLife::PlacedBeforeOperations
        }
        _ => Art8SecondLife::None,
    }
}

/// An EV battery owes 38 mandatory fields and a fresh draft carries almost
/// none, so per-field advisories would put dozens of findings into a document
/// that is stored, signed and served. The publish refusal names them
/// individually, which is where per-field precision is worth its size.
///
/// Portable and SLI batteries produce nothing here: the guidance does not cover
/// them, and `dpp-rules` answers `Unknown` rather than guessing.
fn annex_xiii_content_findings(input: &PluginInput, battery_type: &str) -> Vec<PluginFinding> {
    let mut out = Vec::new();

    let missing: Vec<&str> = mandatory_fields(battery_type)
        .filter(|f| input.get(*f).is_none_or(Value::is_null))
        .collect();
    if !missing.is_empty() {
        out.push(PluginFinding::new(
            "battery.annex_xiii.mandatory_content_incomplete",
            "/",
            format!(
                "{} field(s) the Commission's data-point guidance makes mandatory for a \
                 '{battery_type}' battery are absent, and publishing will be refused until \
                 they are supplied: {}",
                missing.len(),
                missing.join(", ")
            ),
        ));
    }

    // The other half of the table, which nothing checked before: a field the
    // guidance marks "not to be filled/displayed" is not merely surplus. A
    // mandatory-fields check can never notice one, because it is looking for
    // absence.
    let present: Vec<&str> = input
        .as_object()
        .map(|o| o.keys().map(String::as_str).collect())
        .unwrap_or_default();
    for field in fields_not_applicable(&present, battery_type) {
        out.push(PluginFinding::new(
            format!("battery.annex_xiii.{field}_not_applicable"),
            format!("/{field}"),
            format!(
                "'{field}' is declared, but the Commission's data-point guidance marks it \
                 'not to be filled/displayed' for a '{battery_type}' battery — for several \
                 fields because the implementing act that will specify their format has not \
                 been adopted, so a value filed today cannot be the one it will ask for."
            ),
        ));
    }

    out
}

/// Whether the declared state-of-health block is the one Annex VII Part A asks
/// of this battery's category.
///
/// The two lists are disjoint and the asymmetry is easy to get backwards: an
/// electric-vehicle battery reports state of certified energy and nothing else,
/// while stationary storage and LMT batteries report a five-parameter list.
/// Declaring the wrong one is not a missing field — it is the wrong parameter
/// set, which a completeness check cannot see.
fn annex_vii_state_of_health_finding(
    input: &PluginInput,
    battery_type: &str,
) -> Option<PluginFinding> {
    let declared = input.get("stateOfHealth")?.get("parameterSet")?.as_str()?;
    let expected = match annex_vii_parameter_set_for(battery_type)? {
        Annex7ParameterSet::ElectricVehicle => "electricVehicle",
        Annex7ParameterSet::StationaryOrLmt => "stationaryOrLmt",
    };
    if declared == expected {
        return None;
    }
    Some(PluginFinding::new(
        "battery.annex_vii.wrong_state_of_health_parameter_set",
        "/stateOfHealth/parameterSet",
        format!(
            "state of health is declared as '{declared}', but Annex VII Part A asks a \
             '{battery_type}' battery for '{expected}'."
        ),
    ))
}

export_plugin!(BatteryPlugin);

// ─── Tests (host target) ──────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use dpp_plugin_sdk::traits::{AbiVersion, PluginCapability};

    fn valid_battery() -> Value {
        json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 16.0,
            "recycledContentLithiumPct": 6.0
        })
    }

    #[test]
    fn meta_reports_battery_product_group() {
        assert_eq!(BatteryPlugin.meta().product_group, "battery");
    }

    #[test]
    fn capabilities_cover_battery_schema_range() {
        let caps = BatteryPlugin.capabilities();
        assert_eq!(caps.abi_version, AbiVersion::current());
        assert_eq!(caps.supported_schemas[0].max_version, "2.6.0");
        assert!(caps.capabilities.contains(&PluginCapability::Validate));
    }

    #[test]
    fn valid_input_passes_validation() {
        assert!(BatteryPlugin.validate_input(&valid_battery()).is_ok());
    }

    #[test]
    fn missing_gtin_fails_with_field_error() {
        let mut data = valid_battery();
        data.as_object_mut().unwrap().remove("gtin");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        match err {
            PluginError::ValidationErrors(errs) => {
                assert!(
                    errs.iter()
                        .any(|e| e.field == "/gtin" && e.code == "missing")
                );
            }
            other => panic!("expected ValidationErrors, got {other:?}"),
        }
    }

    #[test]
    fn malformed_gtin_fails() {
        let mut data = valid_battery();
        data["gtin"] = json!("12-34");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn non_positive_voltage_fails() {
        let mut data = valid_battery();
        data["nominalVoltageV"] = json!(0.0);
        assert!(BatteryPlugin.validate_input(&data).is_err());
    }

    #[test]
    fn out_of_range_recycled_pct_fails() {
        let mut data = valid_battery();
        data["recycledContentCobaltPct"] = json!(140.0);
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn metrics_surface_all_declared_metals() {
        let result = BatteryPlugin.calculate_metrics(&valid_battery()).unwrap();
        assert_eq!(result.co2e_score(), Some(85.4));
        assert_eq!(
            result.compliance_status,
            PluginComplianceStatus::NotAssessed
        );
        // Four per-metal minima over two measurement bases do not become one
        // number. The flat metric stays unset; the metals travel under `extra`.
        assert_eq!(
            result.recycled_content_pct(),
            None,
            "a mean of the declared metals is not an Art. 8 figure"
        );
        let extra = result.extra.unwrap();
        assert_eq!(extra["recycledContentByMetal"]["cobaltPct"], 16.0);
        assert_eq!(extra["recycledContentByMetal"]["lithiumPct"], 6.0);
        // Undeclared metals are explicitly null, not dropped.
        assert!(extra["recycledContentByMetal"]["nickelPct"].is_null());
    }

    #[test]
    fn metrics_reject_invalid_input() {
        let data = json!({ "batteryChemistry": "LFP" });
        assert!(BatteryPlugin.calculate_metrics(&data).is_err());
    }

    #[test]
    fn generate_passport_is_passthrough_on_valid() {
        let data = valid_battery();
        let out = BatteryPlugin.generate_passport(data).unwrap();
        assert_eq!(out["gtin"], "12345678901231");
    }

    #[test]
    fn nmc_below_2031_cobalt_emits_advisory_warning_not_violation() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "placedOnMarketDate": "2032-01-01", // Phase 1 binds
            "recycledContentCobaltPct": 12.0,   // < 16 Phase-1 target
            "recycledContentNickelPct": 8.0,    // >= 6 ok
            "recycledContentLithiumPct": 6.0    // >= 6 ok
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert_eq!(
            result.compliance_status,
            PluginComplianceStatus::NotAssessed
        );
        // Advisory only, never blocking — the plugin does not gate on Art. 8.
        assert!(result.violations.is_empty());
        let cobalt = result
            .warnings
            .iter()
            .find(|w| w.code.contains("cobalt"))
            .unwrap_or_else(|| panic!("expected cobalt advisory, got: {:?}", result.warnings));
        assert!(
            cobalt.message.contains("binding for this battery"),
            "a battery placed on the market in 2032 is bound by Art. 8(2); got: {}",
            cobalt.message
        );
        assert!(!result.warnings.iter().any(|w| w.code.contains("nickel")));
        assert!(!result.warnings.iter().any(|w| w.code.contains("lithium")));
    }

    #[test]
    fn lfp_zero_cobalt_does_not_warn() {
        // LFP contains no cobalt; a defaulted 0.0 must not produce a shortfall.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "placedOnMarketDate": "2032-01-01",
            "recycledContentReportingYear": 2032,
            "recycledContentCobaltPct": 0.0,
            "recycledContentLithiumPct": 12.5
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result.warnings.is_empty(),
            "LFP cobalt 0.0 must not warn; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn portable_battery_skips_recycled_content_warnings() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "portable",
            "nominalVoltageV": 3.6,
            "nominalCapacityAh": 2.0,
            "expectedLifetimeCycles": 500,
            "co2ePerUnitKg": 5.0,
            "recycledContentCobaltPct": 0.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result.warnings.is_empty(),
            "portable batteries are out of Art. 8(2) Phase-1 scope; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn rated_capacity_unit_error_emits_advisory_warning() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0, // nominal = 4.8 kWh
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "ratedCapacityKwh": 48.0 // 10× off → unit error
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(result.violations.is_empty());
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.rated_capacity.inconsistent_with_nominal"),
            "got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn consistent_rated_capacity_no_warning() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "placedOnMarketDate": "2032-01-01",
            "ratedCapacityKwh": 4.8
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(result.warnings.is_empty(), "got: {:?}", result.warnings);
    }

    #[test]
    fn lmt_battery_below_target_gets_no_phase1_advisory() {
        // LMT (e-bike/e-scooter) batteries are out of Phase-1 scope (Phase 2
        // only, 2036), so a below-2031-target declaration must not be flagged.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "lmt",
            "nominalVoltageV": 36.0,
            "nominalCapacityAh": 10.0,
            "expectedLifetimeCycles": 800,
            "co2ePerUnitKg": 12.0,
            "placedOnMarketDate": "2032-01-01",
            "recycledContentCobaltPct": 5.0 // < 16, but LMT is out of Phase 1
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code.contains("below_2031")),
            "LMT must not get a Phase-1 shortfall advisory; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn battery_placed_before_2031_gets_no_binding_shortfall() {
        // The reason placedOnMarketDate exists. This battery declares 12 %
        // cobalt — below the Art. 8(2) minimum of 16 % — but was placed on the
        // EU market in 2030, so that minimum never attaches to it. Deriving the
        // phase from "today" would report it as short from 18 Aug 2031 onwards.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "placedOnMarketDate": "2030-06-01",
            "recycledContentCobaltPct": 12.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        let cobalt = result
            .warnings
            .iter()
            .find(|w| w.code.contains("cobalt"))
            .unwrap_or_else(|| {
                panic!(
                    "expected forward-looking advisory, got: {:?}",
                    result.warnings
                )
            });
        assert!(
            cobalt.message.contains("not binding for this battery"),
            "a battery placed on the market in 2030 is outside Art. 8(2); got: {}",
            cobalt.message
        );
        assert!(result.violations.is_empty());
    }

    #[test]
    fn missing_market_date_is_reported_rather_than_guessed() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 12.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.market_date_missing"),
            "got: {:?}",
            result.warnings
        );
        // No phase can be determined, so no shortfall may be asserted either way.
        assert!(
            !result.warnings.iter().any(|w| w.code.contains("below_")),
            "no shortfall without a date; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn malformed_market_date_is_treated_as_missing() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "placedOnMarketDate": "01/06/2030",
            "recycledContentCobaltPct": 12.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.market_date_missing"),
            "an unparseable date must not silently become a determination; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn lmt_placed_after_2036_is_bound_by_phase_two() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "lmt",
            "nominalVoltageV": 36.0,
            "nominalCapacityAh": 10.0,
            "expectedLifetimeCycles": 800,
            "co2ePerUnitKg": 12.0,
            "placedOnMarketDate": "2037-01-01",
            "recycledContentCobaltPct": 20.0 // clears 2031's 16 %, short of 2036's 26 %
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        let cobalt = result
            .warnings
            .iter()
            .find(|w| w.code.contains("cobalt"))
            .unwrap_or_else(|| panic!("expected a Phase-2 advisory, got: {:?}", result.warnings));
        assert!(cobalt.code.contains("below_2036"), "got: {}", cobalt.code);
        assert!(
            cobalt.message.contains("binding for this battery"),
            "got: {}",
            cobalt.message
        );
    }

    #[test]
    fn small_industrial_below_target_gets_no_phase1_advisory() {
        // Industrial batteries ≤ 2 kWh are out of Phase-1 scope.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "industrial",
            "nominalVoltageV": 12.0,
            "nominalCapacityAh": 100.0, // 1.2 kWh ≤ 2 kWh
            "expectedLifetimeCycles": 1000,
            "co2ePerUnitKg": 20.0,
            "recycledContentCobaltPct": 5.0 // < 16, but ≤ 2 kWh is out of scope
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code.contains("below_2031")),
            "≤2 kWh industrial must not get a Phase-1 shortfall advisory; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn large_industrial_below_target_gets_phase1_advisory() {
        // > 2 kWh industrial IS in Phase-1 scope.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "industrial",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0, // 4.8 kWh > 2 kWh
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "placedOnMarketDate": "2032-01-01",
            "recycledContentCobaltPct": 5.0 // < 16
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code.contains("cobalt_below_2031")),
            "in-scope industrial shortfall must be flagged; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn cobalt_declared_on_lfp_emits_chemistry_conflict_advisory() {
        // LFP contains no cobalt; a positive cobalt declaration is a data
        // contradiction that must be surfaced, not silently accepted.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "recycledContentCobaltPct": 8.0,
            "recycledContentLithiumPct": 12.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.cobalt_not_in_chemistry"),
            "cobalt-on-LFP must emit a chemistry-conflict advisory; got: {:?}",
            result.warnings
        );
    }
    // ── Annex XIII per-category content ──────────────────────────────────────

    fn codes(result: &PluginResult) -> Vec<&str> {
        result.warnings.iter().map(|w| w.code.as_str()).collect()
    }

    /// A category the guidance covers gets told what it still owes — once.
    #[test]
    fn a_covered_category_is_warned_about_missing_mandatory_content() {
        let mut data = valid_battery();
        data["batteryType"] = json!("ev");
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();

        let hits = codes(&result)
            .into_iter()
            .filter(|c| *c == "battery.annex_xiii.mandatory_content_incomplete")
            .count();
        assert_eq!(
            hits,
            1,
            "one summary finding, not one per field: {:?}",
            codes(&result)
        );

        let msg = &result
            .warnings
            .iter()
            .find(|w| w.code == "battery.annex_xiii.mandatory_content_incomplete")
            .unwrap()
            .message;
        assert!(
            msg.contains("batteryPassportNumber") && msg.contains("manufacturingDate"),
            "the finding must name what is missing: {msg}"
        );
    }

    /// The guidance covers EV, LMT and industrial batteries and says nothing
    /// about portable or SLI ones. Silence is not a requirement to invent.
    #[test]
    fn an_uncovered_category_is_not_warned() {
        let mut data = valid_battery();
        data["batteryType"] = json!("portable");
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !codes(&result).contains(&"battery.annex_xiii.mandatory_content_incomplete"),
            "got: {:?}",
            codes(&result)
        );
    }

    /// The half of the table a completeness check can never see: a field the
    /// guidance says must not be filled, that has been.
    #[test]
    fn a_field_the_guidance_bars_is_flagged_when_present() {
        let mut data = valid_battery();
        data["batteryType"] = json!("lmt");
        data["carbonFootprintClass"] = json!("B");
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            codes(&result).contains(&"battery.annex_xiii.carbonFootprintClass_not_applicable"),
            "got: {:?}",
            codes(&result)
        );

        // Absent, it is not mentioned — the finding is about the value, not the key.
        data.as_object_mut().unwrap().remove("carbonFootprintClass");
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !codes(&result).contains(&"battery.annex_xiii.carbonFootprintClass_not_applicable"),
            "got: {:?}",
            codes(&result)
        );
    }

    // ── Annex VII state of health ────────────────────────────────────────────

    /// Part A's two lists are disjoint, and an EV battery reports the one-item
    /// one. Declaring the five-parameter list is the wrong set, not a gap.
    #[test]
    fn an_ev_battery_declaring_the_stationary_parameter_set_is_flagged() {
        let mut data = valid_battery();
        data["batteryType"] = json!("ev");
        data["stateOfHealth"] = json!({
            "parameterSet": "stationaryOrLmt",
            "remainingCapacityPct": 88.0,
            "selfDischargeRatePctPerMonth": 1.5
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            codes(&result).contains(&"battery.annex_vii.wrong_state_of_health_parameter_set"),
            "got: {:?}",
            codes(&result)
        );

        data["stateOfHealth"] = json!({ "parameterSet": "electricVehicle", "socePct": 97.0 });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !codes(&result).contains(&"battery.annex_vii.wrong_state_of_health_parameter_set"),
            "the set Annex VII Part A actually asks of an EV battery: {:?}",
            codes(&result)
        );
    }

    /// Part A does not reach portable or SLI batteries, so there is no set to
    /// be wrong about.
    #[test]
    fn a_battery_outside_annex_vii_part_a_is_not_flagged() {
        let mut data = valid_battery();
        data["batteryType"] = json!("portable");
        data["stateOfHealth"] = json!({ "parameterSet": "electricVehicle", "socePct": 97.0 });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !codes(&result).contains(&"battery.annex_vii.wrong_state_of_health_parameter_set"),
            "got: {:?}",
            codes(&result)
        );
    }
}

#[cfg(test)]
mod art8_declaration_tests {
    use super::*;

    fn shares_without_year() -> Value {
        json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "placedOnMarketDate": "2032-01-01",
            "recycledContentCobaltPct": 20.0
        })
    }

    #[test]
    fn shares_without_a_reporting_year_are_flagged() {
        let result = BatteryPlugin
            .calculate_metrics(&shares_without_year())
            .unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.reporting_year_missing"),
            "got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn shares_with_a_reporting_year_are_not_flagged() {
        let mut data = shares_without_year();
        data["recycledContentReportingYear"] = json!(2032);
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.reporting_year_missing"),
            "got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn no_shares_declared_means_no_reporting_year_finding() {
        // The duty attaches to declaring a share, not to existing.
        let mut data = shares_without_year();
        data.as_object_mut()
            .unwrap()
            .remove("recycledContentCobaltPct");
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.reporting_year_missing"),
            "got: {:?}",
            result.warnings
        );
    }
}
