package io.odalnode.oracle;

import eu.europa.esig.dss.diagnostic.DiagnosticData;
import eu.europa.esig.dss.enumerations.SignatureForm;
import eu.europa.esig.dss.enumerations.SignatureLevel;
import eu.europa.esig.dss.model.FileDocument;
import eu.europa.esig.dss.simplereport.SimpleReport;
import eu.europa.esig.dss.spi.validation.CommonCertificateVerifier;
import eu.europa.esig.dss.validation.SignedDocumentValidator;
import eu.europa.esig.dss.validation.reports.Reports;

import java.io.File;
import java.util.List;

/**
 * Asks the European Commission's AdES reference implementation what a signature
 * this workspace produced actually is.
 *
 * <h2>Why this exists</h2>
 *
 * The Rust tests for the JAdES module check its output against <em>our own
 * reading</em> of ETSI TS 119 182-1. That reading cites every clause it relies
 * on, but it is still ours — a test built from a transcription agrees with the
 * transcription, including wherever the transcription is wrong. This is the one
 * check available that is not circular.
 *
 * <h2>What it asserts, and what it deliberately does not</h2>
 *
 * <p>Asserted: DSS recognises the artefact as a signature at all, reports its
 * form as {@code JAdES}, and reports its level as {@code JAdES_BASELINE_B}.
 *
 * <p><strong>Not asserted: that the signature is trusted, or qualified.</strong>
 * The artefact is signed under a self-signed certificate generated by the test
 * that produced it. DSS will report it as untrusted, and that is the correct
 * answer — trust comes from a certificate chain to a supervised trust service,
 * and qualified status from a certificate, a creation device and a QTSP
 * together. None of the three is a property of the bytes, and no test can
 * conjure them.
 *
 * <p>So the question this asks is precisely <em>"did we build the structure the
 * standard describes?"</em>, which is the question our own tests cannot answer
 * without begging it.
 */
public final class JadesOracle {

    private static final SignatureForm EXPECTED_FORM = SignatureForm.JAdES;
    private static final SignatureLevel EXPECTED_LEVEL = SignatureLevel.JAdES_BASELINE_B;

    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("usage: jades-oracle <signature-file>");
            System.exit(2);
        }
        File file = new File(args[0]);
        if (!file.isFile()) {
            System.err.printf(
                "no artefact at %s%n"
                + "Generate one first:%n"
                + "  EMIT_JADES_ARTIFACT=1 cargo test -p dpp-crypto --test jades_oracle_artifact%n",
                file.getAbsolutePath());
            System.exit(2);
        }

        System.out.printf("DSS is judging: %s (%d bytes)%n", file.getAbsolutePath(), file.length());

        SignedDocumentValidator validator;
        try {
            validator = SignedDocumentValidator.fromDocument(new FileDocument(file));
        } catch (RuntimeException e) {
            // DSS refuses to build a validator when no reader recognises the
            // document. For our purposes that is the loudest possible failure:
            // it means what we produced is not a signature any AdES
            // implementation can identify.
            System.err.println("DSS does not recognise this document as a signature at all: " + e);
            System.exit(1);
            return;
        }

        // No trust anchors are supplied, deliberately. Supplying a trust store
        // containing our own self-signed certificate would make the run report
        // "trusted", which would be true of nothing outside this process and
        // would quietly turn a structural check into a self-congratulatory one.
        validator.setCertificateVerifier(new CommonCertificateVerifier());

        Reports reports = validator.validateDocument();
        SimpleReport simple = reports.getSimpleReport();
        DiagnosticData diagnostic = reports.getDiagnosticData();

        List<String> signatureIds = simple.getSignatureIdList();
        if (signatureIds.isEmpty()) {
            System.err.println("DSS found no signature in the document.");
            System.err.println(reports.getXmlSimpleReport());
            System.exit(1);
            return;
        }
        if (signatureIds.size() != 1) {
            System.err.printf("expected exactly one signature, DSS found %d%n", signatureIds.size());
            System.exit(1);
            return;
        }

        String id = signatureIds.get(0);
        SignatureLevel level = simple.getSignatureFormat(id);
        SignatureForm form = level == null ? null : level.getSignatureForm();

        System.out.printf("  form:      %s%n", form);
        System.out.printf("  level:     %s%n", level);
        System.out.printf("  indication:%s / %s%n",
            simple.getIndication(id), simple.getSubIndication(id));
        System.out.printf("  signed by: %s%n", diagnostic.getSignedBy(id));

        boolean ok = true;
        if (form != EXPECTED_FORM) {
            System.err.printf("FAIL: expected form %s, DSS reports %s%n", EXPECTED_FORM, form);
            ok = false;
        }
        if (level != EXPECTED_LEVEL) {
            System.err.printf("FAIL: expected level %s, DSS reports %s%n", EXPECTED_LEVEL, level);
            ok = false;
        }

        if (!ok) {
            System.err.println();
            System.err.println("Full DSS simple report:");
            System.err.println(reports.getXmlSimpleReport());
            System.exit(1);
            return;
        }

        System.out.printf("%nOK: DSS reports %s at %s.%n", EXPECTED_FORM, EXPECTED_LEVEL);
        System.out.println(
            "Trust and qualified status are not asserted and are not expected — "
            + "the signing certificate is self-signed by the generating test.");
    }

    private JadesOracle() {
    }
}
