//! Battery sector plugin — EU Battery Regulation 2023/1542.
//!
//! Reference implementation of the [`DppSectorPlugin`] contract on top of
//! `dpp-plugin-sdk`. The crate contains only the plugin's domain logic — the
//! Wasm ABI (`alloc`/`dealloc`/`describe`/`validate`/`calculate_metrics`/
//! `generate_passport`) is generated by [`export_plugin!`].
//!
//! ## Sector vs. product category
//!
//! "battery" is a **sector** — the EU delegated-act bucket the host dispatches
//! on. It is distinct from a *product category* (e.g. `"portable"`,
//! `"industrial"`, `"ev"`), which the Battery Regulation carries as the
//! `batteryType` data field. The sector selects this plugin; the product
//! category is an attribute this plugin may branch on internally. The two are
//! never interchangeable as dispatch keys.

use dpp_plugin_sdk::export_plugin;
use dpp_plugin_sdk::rules::batteries::recycled_content::{
    RecycledContentInput, annex_x_shortfalls_2031, chemistry_regulated_metals,
    recycled_content_chemistry_conflicts,
};
use dpp_plugin_sdk::traits::{
    AbiVersion, DppSectorPlugin, METRIC_CO2E_SCORE, METRIC_RECYCLED_CONTENT_PCT,
    PluginCapabilities, PluginCapability, PluginComplianceStatus, PluginError, PluginFinding,
    PluginInput, PluginMeta, PluginResult, SchemaVersionRange,
};
use dpp_plugin_sdk::validate::{Validator, num};
use serde_json::{Value, json};

#[derive(Default)]
struct BatteryPlugin;

impl DppSectorPlugin for BatteryPlugin {
    fn meta(&self) -> PluginMeta {
        PluginMeta {
            sector: "battery".into(),
            name: "Odal Node Battery Plugin".into(),
            version: env!("CARGO_PKG_VERSION").into(),
            license: "Apache-2.0".into(),
            description: Some(
                "EU Battery Regulation 2023/1542 structural validation and metrics".into(),
            ),
            author: Some("Odal Node".into()),
            homepage: Some("https://github.com/odal-node/dpp-core".into()),
        }
    }

    fn capabilities(&self) -> PluginCapabilities {
        PluginCapabilities {
            abi_version: AbiVersion::current(),
            // Battery schema ships as v1.0.0 and v2.0.0 (Annex XIII fields).
            supported_schemas: vec![SchemaVersionRange {
                min_version: "1.0.0".into(),
                max_version: "2.0.0".into(),
            }],
            capabilities: vec![
                PluginCapability::Validate,
                PluginCapability::ComputeMetrics,
                PluginCapability::GeneratePassport,
            ],
            min_host_version: None,
            max_fuel: None,
            max_memory_bytes: None,
        }
    }

    fn validate_input(&self, input: &PluginInput) -> Result<(), PluginError> {
        Validator::new(input)
            .require_gtin("gtin")
            .require_str("batteryChemistry")
            .require_positive("nominalVoltageV")
            .require_positive("nominalCapacityAh")
            .require_non_negative("co2ePerUnitKg")
            .require_positive_int("expectedLifetimeCycles")
            .optional_pct("recycledContentCobaltPct")
            .optional_pct("recycledContentLithiumPct")
            .optional_pct("recycledContentNickelPct")
            .optional_pct("recycledContentLeadPct")
            .optional_pct("stateOfHealthPct")
            .optional_pct("roundTripEfficiencyPct")
            .finish()
    }

    fn calculate_metrics(&self, input: &PluginInput) -> Result<PluginResult, PluginError> {
        // Metrics are only meaningful for structurally valid input.
        self.validate_input(input)?;

        let co2e = num(input, "co2ePerUnitKg");

        // The Battery Regulation tracks recycled content *per metal* (cobalt,
        // lithium, nickel, lead). The flat `recycled_content_pct` field cannot
        // represent that faithfully, so we expose the mean of declared metals
        // there and the full per-metal breakdown under `extra` — no metal is
        // silently dropped.
        let cobalt = num(input, "recycledContentCobaltPct");
        let lithium = num(input, "recycledContentLithiumPct");
        let nickel = num(input, "recycledContentNickelPct");
        let lead = num(input, "recycledContentLeadPct");

        let declared: Vec<f64> = [cobalt, lithium, nickel, lead]
            .into_iter()
            .flatten()
            .collect();
        let recycled_mean = if declared.is_empty() {
            None
        } else {
            Some(declared.iter().sum::<f64>() / declared.len() as f64)
        };

        let chemistry = input
            .get("batteryChemistry")
            .and_then(Value::as_str)
            .unwrap_or("");
        let battery_type = input
            .get("batteryType")
            .and_then(Value::as_str)
            .unwrap_or("");
        let regulated = chemistry_regulated_metals(chemistry);
        // Energy capacity for the Phase-1 ">2 kWh" scoping threshold: the rated
        // value if given, else nominal V × Ah (both required, so always known).
        let capacity_kwh = num(input, "ratedCapacityKwh").or_else(|| {
            match (
                num(input, "nominalVoltageV"),
                num(input, "nominalCapacityAh"),
            ) {
                (Some(v), Some(ah)) => Some(v * ah / 1000.0),
                _ => None,
            }
        });

        let mut warnings: Vec<PluginFinding> = Vec::new();

        // Data integrity: recycled content declared for a metal the chemistry
        // does not contain (e.g. cobalt on an LFP cell) is a contradiction —
        // surface it as an advisory rather than folding it into the mean silently.
        for metal in recycled_content_chemistry_conflicts(chemistry, cobalt, lithium, nickel, lead)
        {
            let field = match metal {
                "cobalt" => "/recycledContentCobaltPct",
                "lithium" => "/recycledContentLithiumPct",
                "nickel" => "/recycledContentNickelPct",
                "lead" => "/recycledContentLeadPct",
                _ => "",
            };
            warnings.push(PluginFinding::new(
                format!("battery.recycled_content.{metal}_not_in_chemistry"),
                field,
                format!(
                    "Declared {metal} recycled content, but a {chemistry} battery contains \
                     no {metal} — check the declaration."
                ),
            ));
        }

        // Recycled-content target check (EU 2023/1542 Art. 8 + Annex X). Phase-1
        // (from 18 Aug 2031) covers EV, SLI, and industrial batteries > 2 kWh;
        // portable and LMT batteries are out of Phase-1 scope (LMT joins Phase 2
        // in 2036). Applying the Phase-1 minima to an out-of-scope battery would
        // surface a factually wrong "below minimum" advisory. The minima are not
        // binding yet, so in-scope shortfalls are advisory warnings, never
        // blocking violations, and are scoped to the metals the declared
        // chemistry actually contains (an LFP cell has no cobalt/nickel).
        if phase1_in_scope(battery_type, capacity_kwh) {
            let scoped = RecycledContentInput {
                cobalt_pct: if regulated.cobalt { cobalt } else { None },
                lithium_pct: if regulated.lithium { lithium } else { None },
                nickel_pct: if regulated.nickel { nickel } else { None },
                lead_pct: if regulated.lead { lead } else { None },
            };
            for sf in annex_x_shortfalls_2031(&scoped) {
                let field = match sf.material {
                    "cobalt" => "/recycledContentCobaltPct",
                    "lithium" => "/recycledContentLithiumPct",
                    "nickel" => "/recycledContentNickelPct",
                    "lead" => "/recycledContentLeadPct",
                    _ => "",
                };
                warnings.push(PluginFinding::new(
                    format!("battery.recycled_content.{}_below_2031_target", sf.material),
                    field,
                    format!(
                        "Declared {} recycled content {:.1}% is below the EU 2023/1542 \
                         Annex X Phase-1 minimum of {:.0}% (binding from 18 Aug 2031).",
                        sf.material, sf.declared_pct, sf.required_pct
                    ),
                ));
            }
        }

        // Plausibility: rated energy (kWh) vs nominal V×Ah. A gross mismatch
        // (outside [0.5×, 2×]) is almost always a unit-entry error (e.g. Wh
        // typed as kWh). Advisory only — never blocks.
        if let (Some(v), Some(ah), Some(kwh)) = (
            num(input, "nominalVoltageV"),
            num(input, "nominalCapacityAh"),
            num(input, "ratedCapacityKwh"),
        ) {
            let nominal_kwh = v * ah / 1000.0;
            if kwh > 0.0 && nominal_kwh > 0.0 {
                let ratio = kwh / nominal_kwh;
                if !(0.5..=2.0).contains(&ratio) {
                    warnings.push(PluginFinding::new(
                        "battery.rated_capacity.inconsistent_with_nominal",
                        "/ratedCapacityKwh",
                        format!(
                            "Rated capacity {kwh:.2} kWh is inconsistent with nominal \
                             {v}V × {ah}Ah = {nominal_kwh:.2} kWh — check units.",
                        ),
                    ));
                }
            }
        }

        // CO2e compliance thresholds are set by pending delegated acts under
        // Art. 7(2); a binding pass/fail determination is not yet possible, so
        // the status stays NotAssessed and co2e is passed through as a metric.
        let result = PluginResult::new(PluginComplianceStatus::NotAssessed)
            .maybe_metric(METRIC_CO2E_SCORE, co2e)
            .maybe_metric(METRIC_RECYCLED_CONTENT_PCT, recycled_mean)
            .with_extra(json!({
                "recycledContentByMetal": {
                    "cobaltPct": cobalt,
                    "lithiumPct": lithium,
                    "nickelPct": nickel,
                    "leadPct": lead,
                },
                "carbonFootprintClass": input.get("carbonFootprintClass"),
                "batteryType": input.get("batteryType"),
            }));
        Ok(warnings
            .into_iter()
            .fold(result, PluginResult::with_warning))
    }

    fn generate_passport(&self, input: &PluginInput) -> Result<Value, PluginError> {
        // Battery data is stored verbatim once structurally valid; no
        // normalisation is required by the schema today.
        self.validate_input(input)?;
        Ok(input.clone())
    }
}

/// Whether a battery is within EU 2023/1542 Annex X **Phase-1** scope (from
/// 18 Aug 2031): EV, SLI, and industrial batteries with capacity > 2 kWh.
/// Portable and LMT (light means of transport) batteries are excluded — LMT
/// joins only in Phase 2 (2036). An unknown/absent `battery_type` is treated as
/// in-scope, so a mislabelled in-scope battery is not silently skipped.
fn phase1_in_scope(battery_type: &str, capacity_kwh: Option<f64>) -> bool {
    match battery_type.to_ascii_lowercase().as_str() {
        "portable" | "lmt" => false,
        "industrial" => capacity_kwh.is_some_and(|k| k > 2.0),
        _ => true,
    }
}

export_plugin!(BatteryPlugin);

// ─── Tests (host target) ──────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_battery() -> Value {
        json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 16.0,
            "recycledContentLithiumPct": 6.0
        })
    }

    #[test]
    fn meta_reports_battery_sector() {
        assert_eq!(BatteryPlugin.meta().sector, "battery");
    }

    #[test]
    fn capabilities_cover_battery_schema_range() {
        let caps = BatteryPlugin.capabilities();
        assert_eq!(caps.abi_version, AbiVersion::current());
        assert_eq!(caps.supported_schemas[0].max_version, "2.0.0");
        assert!(caps.capabilities.contains(&PluginCapability::Validate));
    }

    #[test]
    fn valid_input_passes_validation() {
        assert!(BatteryPlugin.validate_input(&valid_battery()).is_ok());
    }

    #[test]
    fn missing_gtin_fails_with_field_error() {
        let mut data = valid_battery();
        data.as_object_mut().unwrap().remove("gtin");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        match err {
            PluginError::ValidationErrors(errs) => {
                assert!(
                    errs.iter()
                        .any(|e| e.field == "/gtin" && e.code == "missing")
                );
            }
            other => panic!("expected ValidationErrors, got {other:?}"),
        }
    }

    #[test]
    fn malformed_gtin_fails() {
        let mut data = valid_battery();
        data["gtin"] = json!("12-34");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn non_positive_voltage_fails() {
        let mut data = valid_battery();
        data["nominalVoltageV"] = json!(0.0);
        assert!(BatteryPlugin.validate_input(&data).is_err());
    }

    #[test]
    fn out_of_range_recycled_pct_fails() {
        let mut data = valid_battery();
        data["recycledContentCobaltPct"] = json!(140.0);
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn metrics_surface_all_declared_metals() {
        let result = BatteryPlugin.calculate_metrics(&valid_battery()).unwrap();
        assert_eq!(result.co2e_score(), Some(85.4));
        assert_eq!(
            result.compliance_status,
            PluginComplianceStatus::NotAssessed
        );
        // mean of cobalt(16) + lithium(6) = 11
        assert_eq!(result.recycled_content_pct(), Some(11.0));
        let extra = result.extra.unwrap();
        assert_eq!(extra["recycledContentByMetal"]["cobaltPct"], 16.0);
        assert_eq!(extra["recycledContentByMetal"]["lithiumPct"], 6.0);
        // Undeclared metals are explicitly null, not dropped.
        assert!(extra["recycledContentByMetal"]["nickelPct"].is_null());
    }

    #[test]
    fn metrics_reject_invalid_input() {
        let data = json!({ "batteryChemistry": "LFP" });
        assert!(BatteryPlugin.calculate_metrics(&data).is_err());
    }

    #[test]
    fn generate_passport_is_passthrough_on_valid() {
        let data = valid_battery();
        let out = BatteryPlugin.generate_passport(&data).unwrap();
        assert_eq!(out["gtin"], "12345678901231");
    }

    #[test]
    fn nmc_below_2031_cobalt_emits_advisory_warning_not_violation() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 12.0, // < 16 Phase-1 target
            "recycledContentNickelPct": 8.0,  // >= 6 ok
            "recycledContentLithiumPct": 6.0  // >= 6 ok
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert_eq!(
            result.compliance_status,
            PluginComplianceStatus::NotAssessed
        );
        // Not-in-force threshold ⇒ advisory only, never blocking.
        assert!(result.violations.is_empty());
        assert!(
            result.warnings.iter().any(|w| w.code.contains("cobalt")),
            "expected cobalt advisory, got: {:?}",
            result.warnings
        );
        assert!(!result.warnings.iter().any(|w| w.code.contains("nickel")));
        assert!(!result.warnings.iter().any(|w| w.code.contains("lithium")));
    }

    #[test]
    fn lfp_zero_cobalt_does_not_warn() {
        // LFP contains no cobalt; a defaulted 0.0 must not produce a shortfall.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "recycledContentCobaltPct": 0.0,
            "recycledContentLithiumPct": 12.5
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result.warnings.is_empty(),
            "LFP cobalt 0.0 must not warn; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn portable_battery_skips_recycled_content_warnings() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "portable",
            "nominalVoltageV": 3.6,
            "nominalCapacityAh": 2.0,
            "expectedLifetimeCycles": 500,
            "co2ePerUnitKg": 5.0,
            "recycledContentCobaltPct": 0.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result.warnings.is_empty(),
            "portable batteries are out of Annex X Phase-1 scope; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn rated_capacity_unit_error_emits_advisory_warning() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0, // nominal = 4.8 kWh
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "ratedCapacityKwh": 48.0 // 10× off → unit error
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(result.violations.is_empty());
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.rated_capacity.inconsistent_with_nominal"),
            "got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn consistent_rated_capacity_no_warning() {
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "ratedCapacityKwh": 4.8
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(result.warnings.is_empty(), "got: {:?}", result.warnings);
    }

    #[test]
    fn lmt_battery_below_target_gets_no_phase1_advisory() {
        // LMT (e-bike/e-scooter) batteries are out of Phase-1 scope (Phase 2
        // only, 2036), so a below-2031-target declaration must not be flagged.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "lmt",
            "nominalVoltageV": 36.0,
            "nominalCapacityAh": 10.0,
            "expectedLifetimeCycles": 800,
            "co2ePerUnitKg": 12.0,
            "recycledContentCobaltPct": 5.0 // < 16, but LMT is out of scope
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code.contains("below_2031")),
            "LMT must not get a Phase-1 shortfall advisory; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn small_industrial_below_target_gets_no_phase1_advisory() {
        // Industrial batteries ≤ 2 kWh are out of Phase-1 scope.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "industrial",
            "nominalVoltageV": 12.0,
            "nominalCapacityAh": 100.0, // 1.2 kWh ≤ 2 kWh
            "expectedLifetimeCycles": 1000,
            "co2ePerUnitKg": 20.0,
            "recycledContentCobaltPct": 5.0 // < 16, but ≤ 2 kWh is out of scope
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            !result
                .warnings
                .iter()
                .any(|w| w.code.contains("below_2031")),
            "≤2 kWh industrial must not get a Phase-1 shortfall advisory; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn large_industrial_below_target_gets_phase1_advisory() {
        // > 2 kWh industrial IS in Phase-1 scope.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "NMC",
            "batteryType": "industrial",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0, // 4.8 kWh > 2 kWh
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 5.0 // < 16
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code.contains("cobalt_below_2031")),
            "in-scope industrial shortfall must be flagged; got: {:?}",
            result.warnings
        );
    }

    #[test]
    fn cobalt_declared_on_lfp_emits_chemistry_conflict_advisory() {
        // LFP contains no cobalt; a positive cobalt declaration is a data
        // contradiction that must be surfaced, not silently accepted.
        let data = json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 45.2,
            "recycledContentCobaltPct": 8.0,
            "recycledContentLithiumPct": 12.0
        });
        let result = BatteryPlugin.calculate_metrics(&data).unwrap();
        assert!(
            result
                .warnings
                .iter()
                .any(|w| w.code == "battery.recycled_content.cobalt_not_in_chemistry"),
            "cobalt-on-LFP must emit a chemistry-conflict advisory; got: {:?}",
            result.warnings
        );
    }
}
