//! Battery sector plugin — EU Battery Regulation 2023/1542.
//!
//! Reference implementation of the [`DppSectorPlugin`] contract on top of
//! `dpp-plugin-sdk`. The crate contains only the plugin's domain logic — the
//! Wasm ABI (`alloc`/`dealloc`/`describe`/`validate`/`calculate_metrics`/
//! `generate_passport`) is generated by [`export_plugin!`].
//!
//! ## Sector vs. product category
//!
//! "battery" is a **sector** — the EU delegated-act bucket the host dispatches
//! on. It is distinct from a *product category* (e.g. `"portable"`,
//! `"industrial"`, `"ev"`), which the Battery Regulation carries as the
//! `batteryType` data field. The sector selects this plugin; the product
//! category is an attribute this plugin may branch on internally. The two are
//! never interchangeable as dispatch keys.

use dpp_plugin_sdk::export_plugin;
use dpp_plugin_sdk::traits::{
    AbiVersion, DppSectorPlugin, PluginCapabilities, PluginCapability, PluginComplianceStatus,
    PluginError, PluginInput, PluginMeta, PluginResult, SchemaVersionRange,
    METRIC_CO2E_SCORE, METRIC_RECYCLED_CONTENT_PCT,
};
use dpp_plugin_sdk::validate::{num, Validator};
use serde_json::{json, Value};

#[derive(Default)]
struct BatteryPlugin;

impl DppSectorPlugin for BatteryPlugin {
    fn meta(&self) -> PluginMeta {
        PluginMeta {
            sector: "battery".into(),
            name: "Odal Node Battery Plugin".into(),
            version: env!("CARGO_PKG_VERSION").into(),
            license: "Apache-2.0".into(),
            description: Some(
                "EU Battery Regulation 2023/1542 structural validation and metrics".into(),
            ),
            author: Some("Odal Node".into()),
            homepage: Some("https://github.com/odal-node/dpp-core".into()),
        }
    }

    fn capabilities(&self) -> PluginCapabilities {
        PluginCapabilities {
            abi_version: AbiVersion::current(),
            // Battery schema ships as v1.0.0 and v2.0.0 (Annex XIII fields).
            supported_schemas: vec![SchemaVersionRange {
                min_version: "1.0.0".into(),
                max_version: "2.0.0".into(),
            }],
            capabilities: vec![
                PluginCapability::Validate,
                PluginCapability::ComputeMetrics,
                PluginCapability::GeneratePassport,
            ],
            min_host_version: None,
            max_fuel: None,
            max_memory_bytes: None,
        }
    }

    fn validate_input(&self, input: &PluginInput) -> Result<(), PluginError> {
        Validator::new(input)
            .require_gtin("gtin")
            .require_str("batteryChemistry")
            .require_positive("nominalVoltageV")
            .require_positive("nominalCapacityAh")
            .require_non_negative("co2ePerUnitKg")
            .require_positive_int("expectedLifetimeCycles")
            .optional_pct("recycledContentCobaltPct")
            .optional_pct("recycledContentLithiumPct")
            .optional_pct("recycledContentNickelPct")
            .optional_pct("recycledContentLeadPct")
            .optional_pct("stateOfHealthPct")
            .optional_pct("roundTripEfficiencyPct")
            .finish()
    }

    fn calculate_metrics(&self, input: &PluginInput) -> Result<PluginResult, PluginError> {
        // Metrics are only meaningful for structurally valid input.
        self.validate_input(input)?;

        let co2e = num(input, "co2ePerUnitKg");

        // The Battery Regulation tracks recycled content *per metal* (cobalt,
        // lithium, nickel, lead). The flat `recycled_content_pct` field cannot
        // represent that faithfully, so we expose the mean of declared metals
        // there and the full per-metal breakdown under `extra` — no metal is
        // silently dropped.
        let metals = [
            ("cobaltPct", num(input, "recycledContentCobaltPct")),
            ("lithiumPct", num(input, "recycledContentLithiumPct")),
            ("nickelPct", num(input, "recycledContentNickelPct")),
            ("leadPct", num(input, "recycledContentLeadPct")),
        ];
        let declared: Vec<f64> = metals.iter().filter_map(|(_, v)| *v).collect();
        let recycled_mean = if declared.is_empty() {
            None
        } else {
            Some(declared.iter().sum::<f64>() / declared.len() as f64)
        };

        // CO2e compliance thresholds are set by pending delegated acts under
        // Art. 7(2); a pass/fail determination is not yet possible.
        Ok(PluginResult::new(PluginComplianceStatus::NotAssessed)
            .maybe_metric(METRIC_CO2E_SCORE, co2e)
            .maybe_metric(METRIC_RECYCLED_CONTENT_PCT, recycled_mean)
            .with_extra(json!({
                "recycledContentByMetal": {
                    "cobaltPct": metals[0].1,
                    "lithiumPct": metals[1].1,
                    "nickelPct": metals[2].1,
                    "leadPct": metals[3].1,
                },
                "carbonFootprintClass": input.get("carbonFootprintClass"),
                "batteryType": input.get("batteryType"),
            })))
    }

    fn generate_passport(&self, input: &PluginInput) -> Result<Value, PluginError> {
        // Battery data is stored verbatim once structurally valid; no
        // normalisation is required by the schema today.
        self.validate_input(input)?;
        Ok(input.clone())
    }
}

export_plugin!(BatteryPlugin);

// ─── Tests (host target) ──────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_battery() -> Value {
        json!({
            "gtin": "12345678901231",
            "batteryChemistry": "LFP",
            "nominalVoltageV": 48.0,
            "nominalCapacityAh": 100.0,
            "expectedLifetimeCycles": 3000,
            "co2ePerUnitKg": 85.4,
            "recycledContentCobaltPct": 16.0,
            "recycledContentLithiumPct": 6.0
        })
    }

    #[test]
    fn meta_reports_battery_sector() {
        assert_eq!(BatteryPlugin.meta().sector, "battery");
    }

    #[test]
    fn capabilities_cover_battery_schema_range() {
        let caps = BatteryPlugin.capabilities();
        assert_eq!(caps.abi_version, AbiVersion::current());
        assert_eq!(caps.supported_schemas[0].max_version, "2.0.0");
        assert!(caps.capabilities.contains(&PluginCapability::Validate));
    }

    #[test]
    fn valid_input_passes_validation() {
        assert!(BatteryPlugin.validate_input(&valid_battery()).is_ok());
    }

    #[test]
    fn missing_gtin_fails_with_field_error() {
        let mut data = valid_battery();
        data.as_object_mut().unwrap().remove("gtin");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        match err {
            PluginError::ValidationErrors(errs) => {
                assert!(errs
                    .iter()
                    .any(|e| e.field == "/gtin" && e.code == "missing"));
            }
            other => panic!("expected ValidationErrors, got {other:?}"),
        }
    }

    #[test]
    fn malformed_gtin_fails() {
        let mut data = valid_battery();
        data["gtin"] = json!("12-34");
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn non_positive_voltage_fails() {
        let mut data = valid_battery();
        data["nominalVoltageV"] = json!(0.0);
        assert!(BatteryPlugin.validate_input(&data).is_err());
    }

    #[test]
    fn out_of_range_recycled_pct_fails() {
        let mut data = valid_battery();
        data["recycledContentCobaltPct"] = json!(140.0);
        let err = BatteryPlugin.validate_input(&data).unwrap_err();
        assert!(matches!(err, PluginError::ValidationErrors(_)));
    }

    #[test]
    fn metrics_surface_all_declared_metals() {
        let result = BatteryPlugin.calculate_metrics(&valid_battery()).unwrap();
        assert_eq!(result.co2e_score(), Some(85.4));
        assert_eq!(result.compliance_status, PluginComplianceStatus::NotAssessed);
        // mean of cobalt(16) + lithium(6) = 11
        assert_eq!(result.recycled_content_pct(), Some(11.0));
        let extra = result.extra.unwrap();
        assert_eq!(extra["recycledContentByMetal"]["cobaltPct"], 16.0);
        assert_eq!(extra["recycledContentByMetal"]["lithiumPct"], 6.0);
        // Undeclared metals are explicitly null, not dropped.
        assert!(extra["recycledContentByMetal"]["nickelPct"].is_null());
    }

    #[test]
    fn metrics_reject_invalid_input() {
        let data = json!({ "batteryChemistry": "LFP" });
        assert!(BatteryPlugin.calculate_metrics(&data).is_err());
    }

    #[test]
    fn generate_passport_is_passthrough_on_valid() {
        let data = valid_battery();
        let out = BatteryPlugin.generate_passport(&data).unwrap();
        assert_eq!(out["gtin"], "12345678901231");
    }
}
